### ISSUE TITLE
the last "docker run"  is right?

### ISSUE THREAD

**Issue by zhang-xinsheng** [m1k1o/win10-in-docker#1]
docker run -d --name win10-in-docker \
	-p 5901:5901 \
	--privileged --cap-add=ALL \
	-v /lib/modules:/lib/modules \
	-v /dev:/dev \
	-v $PWD/Win10_2004_English_x64.iso:/home/arch/win10_x64.iso \
	-v $PWD/win10.img:/home/arch/win10_hdd.img \
	win10

-v $PWD/win10.img:/home/arch/win10_hdd.img \              shall be 
-v $PWD/win10_hdd.img:/home/arch/win10_hdd.img \

**Comment by m1k1o** [comment]
True. Thanks, I'll fix that.
